name: XGraphQLtest
options:
  minimumXcodeGenVersion: 2.44.0
  developmentLanguage: ja
  xcodeVersion: 16.0
settings:
  base:
    SWIFT_VERSION: 6.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
packages:
  XGraphQLkit:
    path: .
targets:
  XGraphQLtest:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App/Sources
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: XGraphQLtest
        UILaunchScreen:
          UIColorName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        DEVELOPMENT_TEAM: L8K7QM3JD5
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: jp.yyyywaiwai.CDXWidgettest
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: XGraphQLkit
        product: XGraphQLkit
schemes:
  XGraphQLtest:
    build:
      targets:
        XGraphQLtest: all
    run:
      config: Debug
    test:
      config: Debug
